---
- hosts: scoldham2
  become: yes
  handlers:
    - name: restart apache
	  service: name="httpd" state="restarted"
	  listen: "restart web"
  tasks:
    - name: change config
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^DocumentRoot.*S'
		replace: 'DocumentRoot "/opt/www"'
		backup: yes
	  notify: "restart apache"